#https://www.youtube.com/watch?v=S8uQF4kWFkw
#https://www.google.com/search?q=C2+through+C4+scale+piano&tbm=isch&ved=2ahUKEwiozIrqq6T5AhXAKjQIHY2SDigQ2-cCegQIABAA&oq=C2+through+C4+scale+piano&gs_lcp=CgNpbWcQA1DeBFiGFmD8F2gBcAB4AIABP4gBrwSSAQIxMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=ehjnYqinHMDV0PEPjaW6wAI&bih=937&biw=1920#imgrc=o7yh9eLBZZyEFM
#Stranger Things Theme by Kyle Dixon and Michael Stein of the electronic band Survive

with_synth :pluck do
  with_fx :echo, pre_mix: 0.2 do
    with_fx :rlpf do
      play :C2, sustain: 500
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      play :C2, sustain: 500
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      play :C2, sustain: 500
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :D2, sustain: 500
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3, sustain: 500
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      play :G2, sustain: 500
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      play :C2, sustain: 500
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      play :D2, sustain: 500
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      play :C2, sustain: 500
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :B1, sustain: 500
      sleep 0.3
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.8
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
      sleep 0.3
      play :C2, sustain: 500
      sleep 0.3
      play :E3
      sleep 0.3
      play :G3
      sleep 0.3
      play :B3
      sleep 0.3
      play :C4
      sleep 0.3
      play :B3
      sleep 0.3
      play :G3
      sleep 0.3
      play :E3
    end
  end
end
